name: Manual Workflow
on: 
  workflow_dispatch:
    inputs:
      build:
        description: Build
        type: string
        required: true

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
    - run: echo "Процесс запущен вручную! Build - ${{ github.event.inputs.build}}"

    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Setup Gradle 8.10
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      with:
        gradle-version: '8.10'

    # - name: Setup Gradle Wrapper
    #   run: gradle wrapper --gradle-version 8.10

    - name: Build statify-velocity with Gradle Wrapper
      working-directory: statify-velocity
      run: |
        gradle wrapper --gradle-version 8.10
        ./gradlew clean shadowJar

    - name: Build statify-paper with Gradle Wrapper
      working-directory: statify-paper
      run: |
        gradle wrapper --gradle-version 8.10
        ./gradlew clean shadowJar

    - name: Build statify-fabric with Gradle Wrapper
      working-directory: statify-fabric
      run: |
        gradle wrapper --gradle-version 8.10
        ./gradlew clean build

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Set build
      uses: actions/upload-artifact@v7
      with:
        name: Statify
        path: 
          statify-velocity/build/libs/*.jar
          statify-paper/build/libs/*.jar
          statify-fabric/build/libs/*.jar